### ISSUE TITLE
Code problems about Graph-Skeleton

### ISSUE THREAD

**Issue by Zhuofeng-Li** [caolinfeng/GraphSkeleton#1]
Hi, thank you for your work in graph skeleton. 

However, there are some problems in your codes. Your path is set as the aboulte path, like this `/home/caolinfeng/clf/xinye/GraphSkeleton/skeleton_compress`. So the whole codes not work.

Would you mind sharing your python version or a graph_skeleton.so which can be used directly in python?
![image](https://github.com/caolinfeng/GraphSkeleton/assets/89558990/6586b125-fd7c-41c4-b85c-f8513e0dcaee)

**Comment by HaoranDeng** [comment]
We addressed these issues in the latest commit. Thank you for your feedback.
